
name: The CI file

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    Containerize-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Login to docker
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKER_HUB_USER }}
                password: ${{ secrets.DOCKER_HUB_PAT }}
            
            - name: Setup docker build
              uses: docker/setup-buildx-action@v3 

            - name: Containerize and push the app
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ${{ vars.DOCKER_HUB_USER }}/mindwave:v1
          
    Deploy-job:
      needs: 
        - Containerize-job
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDS }}


        - name: Start and stop container app
          uses: azure/cli@v2
          with:
            azcliversion: latest
            inlineScript: |
              az containerapp revision copy -n ${{ vars.CURR_NAME }} -g ${{ vars.CURR_RG}} --image ${{ vars.DOCKER_HUB_USER }}/mindwave:v1
      
           
    
